server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlite:lib/sample2.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl: none
      ddl-auto: none
